### ISSUE TITLE
how to splite log file with regular time range?

### ISSUE THREAD

**Issue by jeffie** [cihub/seelog#146]
i want to split log files with regular time range,such as 15min/file.  files like this: a.log.201702130100,a.log.201702130115

**Comment by lwithers** [comment]
Take a look at the docs under https://github.com/cihub/seelog/wiki/Receiver-reference#rolling-file-writer-or-rotation-file-writer and in particular set `type` to `date` and view the docs of the `datepattern` attribute. I'm not sure that it lets you do 15 minute boundaries, due to the way it constructs the filenames, but you can certainly do 1-hour boundaries.

**Comment by gqlxj1987** [comment]
if i would want to 15 minute boundaries, can there is some way to do this?

**Comment by jeffie** [comment]
@gqlxj1987 it`s no api to support this feature in currtent version,i think you can split the file use the  extra shell
