### ISSUE TITLE
rename date rolling log till date changed

### ISSUE THREAD

**Issue by chy168** [cihub/seelog#91]
Hi,

I configured my application for logging date rolling log.

````
<outputs formatid="main">
        <console />
        <rollingfile type="date" filename="/var/log/test/api.log" datepattern="02.01.2006" maxrolls="14" />
</outputs>
````

For sure, the output file will be named as "api.log.25.06.2015", "api.log.24.06.2015" ... etc.

Assumption today is "25.06.2015".
May I know if any possible always to write today's log to "api.log" until the date changed to "26.06.2015".
It will rename the old log file "api.log" to "api.log.25.06.2015", and then start a new "api.log".

Thank you!

**Comment by goodsign** [comment]
Hi!

For simplicity, seelog doesn't have this feature and it is not planned. 

Because when you shut down your program and then start it again later (in a couple of days), you cannot know what date 'api.log' corresponds to. So, if you want this feature, you would need to store the 'date of api.log' in some other place (like a second file) or try to guess it using modification time (which is unreliable, because you may not have modified it for a long time). Both of these options make things harder and such feature just isn't worth it.
