### ISSUE TITLE
How to create custom json log message format?

### ISSUE THREAD

**Issue by debraj-manna** [cihub/seelog#93]
Is the below log message:-

```json
{"level":"info", "message" : "hello world", "tId":"T12345", "reqId" : "R3232", "appId": "Discovery", "sessionId": "12325", "userId":"AB3435", "stackTraces" : ["Call Trace 1", "Call Trace 2"],  "timestamp" : "2015-07-09T18:00:00.875Z"}
```
where along with `message`, `tId`, `reqId` `appId`,  `sessionId` and `userId` will be passed by caller.

Is it possible to achieve this using custom formatter?

**Comment by goodsign** [comment]
Hi!

If those `tId`, `reqId` and others are dynamic, then currently this is not possible to do with custom formatters, because you can only use this context info in custom formatter handlers:

```go
// Represents runtime caller context.
type LogContextInterface interface {
	// Caller's function name.
	Func() string
	// Caller's line number.
	Line() int
	// Caller's file short path (in slashed form).
	ShortPath() string
	// Caller's file full path (in slashed form).
	FullPath() string
	// Caller's file name (without path).
	FileName() string
	// True if the context is correct and may be used.
	// If false, then an error in context evaluation occurred and
	// all its other data may be corrupted.
	IsValid() bool
	// Time when log function was called.
	CallTime() time.Time
}
```

But, we can think of solving this, probably it is possible to extend the `LogContextInterface` with something like `CustomContext interface{}` so that you could be able to do something like this:

```go
    logger, err := log.LoggerFromSomething(...);
    if err != nil {
        return nil, err
    }
...
    logger.SetContext(&SomeContext{tId, reqId, appId, sessionId, userId});
...
   logger.Debug(...);
```

If such a feature could be implemented, then yes, such a custom formatter could be possible, because you set the context and it is available through the `LogContextInterface`:

```go
func createTIdFormatter(params string) log.FormatterFunc {
    return func(message string, level log.LogLevel, context log.LogContextInterface) interface{} {
       myContext, _ := entity.(SomeContext)
       return myContext.tId
    }
}

func init() {
    err := log.RegisterCustomFormatter("TID", createTIdFormatter)
    if err != nil {
         ...
    }
}
```

and then you could use it in your configs:

```xml
<seelog type="sync">
    <outputs formatid="main">
        <console/>
    </outputs>
    <formats>
        <format id="main" format="%TID %Msg%n"/>
    </formats>
</seelog>
```

If that feature is needed, I'll be able to look at it in a couple of weeks. 

If you need it faster, then you could help with a PR. Basically, you just need to add some `customContext` field to [commonLogger](https://github.com/cihub/seelog/blob/master/logger.go#L128), add `SetContext` to [LoggerInterface](https://github.com/cihub/seelog/blob/master/logger.go#L39) and implement it for `commonLogger`, so that it just writes to the `customContext` field. Then you just have to add `CustomContext` to [LogContextInterface](https://github.com/cihub/seelog/blob/master/common_context.go#L46) and `customContext` field to [logContext](https://github.com/cihub/seelog/blob/master/common_context.go#L110) and [errorContext](https://github.com/cihub/seelog/blob/master/common_context.go#L148). Last step is to change [specifyContext](https://github.com/cihub/seelog/blob/master/common_context.go#L95) and add `customContext` as a parameter and then [here](https://github.com/cihub/seelog/blob/master/logger.go#L285) change the  `specifyContext(stackCallDepth + cLogger.addStackDepth)` call to specifyContext(stackCallDepth + cLogger.addStackDepth, cLogger.customContext).

But if you could wait, I'll do it myself in August.

**Comment by debraj-manna-jabong** [comment]
Thanks @goodsign . I will give it a try.

**Comment by debraj-manna** [comment]
I will give it a try. Thanks @goodsign  for pointing me to the relevant code sections.

**Comment by mmindenhall** [comment]
I'm using seelog in development of a new product.  We just had a new requirement to be able to forward logs to an aggregator (e.g., graylog, logstash), which is typically done via JSON structured logs.  It would be really great to have improved support for this.

What's been discussed so far on this issue is the ability to set a custom context on a logger, which will add those fields to every log message.  I think this does not quite go far enough, as there would also be a need to add custom fields per log message.  I'd love to see something similar to the [log15](https://github.com/inconshreveable/log15) library:

This is the `Ctx` type declaration:
```go
type Ctx map[string]interface{}
```
Which can then be used to set key/value pairs on the logger (global to all log messages created by the logger), and/or the log message (unique to the log message):

```go
srvlog := log.New(log.Ctx{"module": "app/server"})
srvlog.Warn("abnormal conn rate", log.Ctx{"rate": curRate, "low": lowRate, "high": highRate})
```

**Comment by goodsign** [comment]
Hey!
Basically, this is possible, however we should think about not getting too complex and trying to fit all possible features into one package and ending up with a cluttered interface.

I haven't had a chance to look at the issues in August, because I had to leave for another couple of months, unfortunately (until October). So, PRs are still accepted.

**Comment by goodsign** [comment]
Probably we could start with a logger-level context and then think about message-level context.

**Comment by goodsign** [comment]
Hey!

I returned to my normal schedule, so I'm going to look at this issue today, stay tuned.

**Comment by goodsign** [comment]
I've added `SetContext` to `LoggerInterface`. You can now use it to set custom context to any interface and then call `CustomContext` on `LogContextInterface` to get it inside your formatter. Please check it out and tell me if everything is ok.

**Comment by shafreeck** [comment]
Hi @goodsign  I am using seelog in our new project and it is really a powerful log library. However, I got stuck on this problem too. I am afraid the `custom context` way maybe not as useful as you think. In our situation, there are many concurrent goroutines using a shared logger. So I cannot just call logger.SetContext in one goroutine because this may overwrite the context of another. Do you have suggestions about how to solving this ?

**Comment by goodsign** [comment]
Hi @shafreeck!

Usually the seelog way of handling such cases is one logger per goroutine/per handler/etc. In our examples we show web servers creating a logger per request. For performance issues I thought about implementing the fast copy for loggers (to avoid deserializing from config every time).

We don't have other means to do this at the moment.

**Comment by goodsign** [comment]
If that's too much overhead, let's think about possible solutions. Maybe we could take the idea described above and allow ```&Context``` as last parameter to any of the existing funcs. For example, now you do:

```go
seelog.Debugf("Something %s: %s", string1, string2)
```

, but you can possibly do it this way:

```go
seelog.Debugf("Something %s: %s", string1, string2, seelog.CustomContext{something: "smth1", something2: "smth2"})
```

Let me know what you think.

**Comment by shafreeck** [comment]
@goodsign I did not see the web server example you mentioned above. Could you give me a link address? I think the optional context argument is a good idea. It is compatible with the original apis and supplies a powerful way to custom the log format. However , there is also something painful, users have to pass `context` as argument every call of logging.

**Comment by goodsign** [comment]
This is the [example](https://github.com/cihub/seelog/wiki/custom-receivers#note-about-google-app-engine-integration) I was talking about. 

Yeah, that's why currently the main path is setting the context, but it may not work for complex asynchronous cases with multiple goroutines with one logger.

**Comment by skypacer210** [comment]
@goodsign 
Thanks your great seelog library!
It seems that the struct named cfgParseParams can't be exported in current version.
Please refer to your examples: "parserParams := &log.CfgParseParams{", here is CfgParseParams.
Do you plan exported the CfgParseParams struct? Thanks.

**Comment by goodsign** [comment]
Hey @skypacer210,

Made it exported, check it out!

**Comment by goodsign** [comment]
Hey @debraj-manna,

This issue was left here for a while, but I believe I've implemented what was needed, so I'm closing the issue now, please reopen if needed.

**Comment by skypacer210** [comment]
Got it, thanks @goodsign !
