### ISSUE TITLE
'Max rolls' feature for 'rolling' receiver with type='date' do not work for me.

### ISSUE THREAD

**Issue by wujunbin** [cihub/seelog#96]
'Max rolls' feature for 'rolling' receiver with type='date' do not work for me.
my code is follow.
```
	testConfig := `
<seelog>
	<outputs>
		<rollingfile type="date" filename="./log/roll.log" maxrolls="5" datepattern="02.01.2006"/>
	</outputs>
</seelog>
`
	logger, _ := log.LoggerFromConfigAsBytes([]byte(testConfig))
	log.ReplaceLogger(logger)
	fmt.Println("Rolling file writer")
	for i := 0; i < 10000; i++ {
		log.Tracef("%d", i)
		log.Infof("%d", i)
	}
```

![image](https://cloud.githubusercontent.com/assets/11531884/10363445/1aefb590-6de7-11e5-8f70-b7817c56721d.png)

the value of 'maxrolls' is 5. it should at most generate five files but there are six log file.
Is wrong the usage i used to log?
How can i fix the problem.

**Comment by goodsign** [comment]
Hi!

Before version 2.3 this attribute was not applicable to the 'date' rolling writer. Could it be that you use older version or is the same happening on the latest one too?

**Comment by wujunbin** [comment]
Hi！
I just use the command "go get -u github.com/cihub/seelog", so it shoud be the latest version.

**Comment by wujunbin** [comment]
it still generate 6 files in the latest version.

**Comment by goodsign** [comment]
I think it can take the `go1.0` tagged revision even with -u flag. Can you go to your go path folder, find the seelog folder, check whar revision is active and do manual git checkout to the latest revision?

I think the issue is with 'go1.0' tag, I believe you are still getting the wrong revision with `go get`. If that is the case, I'll test whether it is compatible and retag the latest revision.

**Comment by wujunbin** [comment]
i think i am in the latest version. 
![image](https://cloud.githubusercontent.com/assets/11531884/10364474/437d8a58-6dee-11e5-97d7-339e4f384d47.png)

the image above is a capture of sourcetree that shows the code of seelog is in the latest version.

**Comment by goodsign** [comment]
Hmm, ok, then it looks like a bug. I'll look into it, thanks for submitting.

**Comment by goodsign** [comment]
Hey, sorry for long response, I just had time to look into the issue.

Well, basically it can be considered a bug or a feature depending on the definitions. Basically, you have primary file + 5 roll files. So, 6 files total.

When the rolling logger type is 'size', it looks absolutely fine:

```
file.log     <- current
file.log.1  <- roll 1
file.log.2  <- roll 2
file.log.3  <- roll 3
file.log.4  <- roll 4
file.log.5  <- roll 5
```

But when you use time rolling, maybe it looks like a bit unintuitive:

```
roll.log.06.11.2015  <- current
roll.log.05.11.2015  <- roll 1
roll.log.04.11.2015  <- roll 2
roll.log.03.11.2015  <- roll 3
roll.log.02.11.2015  <- roll 4
roll.log.01.11.2015  <- roll 5
```

But basically it's the same scheme: one 'current file' and five 'roll files'.

Now, after some thinking, maybe I would say that it is not a bug after all, because probably it is better to have common behavior in 'size' and 'time' loggers.

You can fix the problem by using maxrolls='4' instead of 5.

**Comment by wujunbin** [comment]
I think it is a bug. The code I wrote can generate many files. The num of files is greater than 6.
![image](https://cloud.githubusercontent.com/assets/11531884/10876622/3c902216-8179-11e5-8447-c5f689a20fc7.png)

**Comment by goodsign** [comment]
Probably it's connected with the fact that your program doesn't run longer than one roll period. I made a quick fix. Try the latest revision now.

**Comment by wujunbin** [comment]
It's fine now. you are right. I run the program many times by entering go
run *.go on command line. it doesn't run longer than one roll period.

Thanks.

2015-11-02 17:12 GMT+08:00 goodsign <notifications@github.com>:
